import { describe, it, expect } from 'vitest';
import rules from '../data/rules.json';

// data/rules.json is generated by scripts/build-rules.js from the SRD 5.2
// sources in scripts/srd/. These tests guard the generated output's contract
// with its two consumers: src/ai/rules.js (scene-scoped prompt injection) and
// the Compendium's Rules tab. If a build-script change breaks one of these,
// the failure should land here, not in play.

// Everything detectContext()/classifyText() in src/ai/rules.js can produce,
// plus 'reference' (browsable in the Compendium, never injected).
const CONTEXTS = ['any', 'combat', 'rolling', 'rest', 'exploration', 'spellcasting', 'social', 'reference'];

// Pinned by name in src/ai/rules.js — renaming them in the build silently
// unpins them from the injection budget's priority slot.
const CORE_RULES = ['When to Roll', 'DC Guidelines', 'Ability Checks'];

const estTokens = (t) => Math.ceil(t.length / 4);

describe('rules.json (generated)', () => {
  it('has full-book coverage, not a hand-written subset', () => {
    expect(rules.length).toBeGreaterThan(150);
  });

  it('every entry satisfies the consumer contract', () => {
    for (const e of rules) {
      expect(e.name, JSON.stringify(e).slice(0, 80)).toBeTruthy();
      expect(e.content?.trim()).toBeTruthy();
      expect(e.type).toBeTruthy(); // pullRules() filters on type !== undefined
      expect(Array.isArray(e.context) && e.context.length > 0, `${e.name} context`).toBe(true);
      for (const c of e.context) expect(CONTEXTS, `${e.name}: context "${c}"`).toContain(c);
    }
  });

  it('has no duplicate names (pullRules dedupes by name — a dupe silently shadows)', () => {
    const names = rules.map(e => e.name);
    expect(new Set(names).size).toBe(names.length);
  });

  it('keeps the CORE_RULES entries rules.js pins by name', () => {
    const names = new Set(rules.map(e => e.name));
    for (const core of CORE_RULES) expect(names.has(core), core).toBe(true);
  });

  it('contains no unconverted HTML', () => {
    for (const e of rules) {
      expect(/<table|<tr|<td|<th|<\/t/i.test(e.content), `${e.name} has HTML`).toBe(false);
    }
  });

  it('no single entry can swallow the whole 1500-token injection budget', () => {
    for (const e of rules) {
      expect(estTokens(e.content), `${e.name} ~${estTokens(e.content)} tokens`).toBeLessThan(900);
    }
  });

  it('carries the 2024-edition rules the code enforces (edition-drift guard)', () => {
    const by = Object.fromEntries(rules.map(e => [e.name, e]));
    // RollBar's exhaustionPenalty() is -2 per level (2024) — the old curated
    // entry taught the 2014 six-tier table and is superseded.
    expect(by['Exhaustion [Condition]'].content).toMatch(/reduced by 2 times your Exhaustion level/i);
    expect(by['Exhaustion']).toBeUndefined();
    // 2024 Surprise is Disadvantage on Initiative, not losing the first turn.
    expect(by['Surprise'].content).toMatch(/Disadvantage on its Initiative roll/i);
  });

  it('never injects meta terms — reference entries stay out of the prompt path', () => {
    const by = Object.fromEntries(rules.map(e => [e.name, e]));
    for (const name of ['Campaign', 'Alignment', 'Character Sheet', 'Stat Block']) {
      expect(by[name].context, name).toEqual(['reference']);
    }
  });
});
