import { createSignal, For, Show } from 'solid-js';
import { validateBundle } from '../../content/bundleNormalizer.js';
import { importBundle } from '../../data/bundles.js';
import { callProvider } from '../../ai/providers.js';
import { BUNDLE_BUILDER_SYSTEM } from '../../ai/setupPrompts.js';

const CONTENT_LABELS = {
  adventures: 'Adventures',
  encounters: 'Encounters',
  npcs: 'NPCs',
  locations: 'Locations',
  aiGuidance: 'AI Guidance',
  dmTools: 'DM Tools',
};

// Bundle import flow — two entry paths (pick a file, or build with AI) that
// both funnel into the same parse → preview → confirm pipeline, mirroring
// Settings.jsx's handleImportFile()/importGame() pattern for the file path
// and CharCreate.jsx's AIBuilder for the AI path. The AI path never gets a
// trusted write of its own — its BUNDLE_JSON output hits validateBundle()
// exactly like a hand-authored file would.
export default function ContentImport({ onBack }) {
  const [mode, setMode] = createSignal(null); // null | 'file' | 'ai'
  const [parsed, setParsed] = createSignal(null); // { valid, errors, warnings, normalized }
  const [rawJson, setRawJson] = createSignal(null);
  const [busy, setBusy] = createSignal(false);
  let fileInput;

  function pickFile() {
    fileInput?.click();
  }

  function handleGenerated(json) {
    setRawJson(json);
    setParsed(validateBundle(json));
  }

  async function handleFile(e) {
    const file = e.target.files?.[0];
    e.target.value = '';
    if (!file) return;
    try {
      const text = await file.text();
      const json = JSON.parse(text);
      handleGenerated(json);
    } catch (err) {
      setRawJson(null);
      setParsed({ valid: false, errors: ['Not valid JSON: ' + (err.message || 'parse error')], warnings: [] });
    }
  }

  async function confirmImport() {
    const raw = rawJson();
    if (!raw) return;
    setBusy(true);
    const result = await importBundle(raw);
    setBusy(false);
    if (!result.ok) {
      window.dispatchEvent(new CustomEvent('toast', { detail: { text: 'Import failed: ' + result.errors.join(', '), type: 'error' } }));
      return;
    }
    window.dispatchEvent(new CustomEvent('toast', { detail: { text: `Imported "${result.bundle.name}"` } }));
    onBack?.();
  }

  function reset() {
    setParsed(null);
    setRawJson(null);
    setMode(null);
  }

  return (
    <div class="settings-page">
      <div class="settings-subheader">
        <button class="btn-back" onClick={parsed() || mode() ? reset : onBack}><i class="ph ph-caret-left" /> Back</button>
        <h2 class="settings-heading">Import Bundle</h2>
      </div>

      {!parsed() && !mode() && (
        <section class="settings-section">
          <p class="settings-hint">Pick a bundle JSON file, or build one with AI (adventures, encounters, NPCs, locations, AI guidance, DM tools).</p>
          <button class="btn-import" onClick={pickFile}>Choose Bundle File</button>
          <input ref={fileInput} type="file" accept=".json" class="import-file-input" onChange={handleFile} />
          <button class="btn-import" onClick={() => setMode('ai')}>Build with AI</button>
        </section>
      )}

      {!parsed() && mode() === 'ai' && (
        <BundleAIBuilder onGenerated={handleGenerated} />
      )}

      {parsed() && !parsed().valid && (
        <section class="settings-section">
          <p class="settings-hint" style="color: var(--color-danger, #d33)">Couldn't import this file:</p>
          <ul>
            {parsed().errors.map(e => <li>{e}</li>)}
          </ul>
          <button class="btn-import" onClick={reset}>Try Another File</button>
        </section>
      )}

      {parsed() && parsed().valid && (
        <section class="settings-section">
          <h3 class="settings-label">{parsed().normalized.name}</h3>
          <p class="settings-hint">
            v{parsed().normalized.version} · by {parsed().normalized.author}
          </p>
          {parsed().normalized.description && <p class="settings-hint">{parsed().normalized.description}</p>}

          <ul>
            {Object.entries(CONTENT_LABELS).map(([key, label]) => {
              const count = parsed().normalized.content[key]?.length || 0;
              return count > 0 ? <li>{label}: {count}</li> : null;
            })}
          </ul>

          {parsed().warnings.length > 0 && (
            <>
              <p class="settings-hint">{parsed().warnings.length} item(s) skipped:</p>
              <ul>
                {parsed().warnings.slice(0, 10).map(w => <li>{w}</li>)}
              </ul>
            </>
          )}

          <p class="settings-hint">{mode() === 'ai' ? 'Generated by AI' : 'Imported from your file'} — review before confirming.</p>
          <button class="btn-export" disabled={busy()} onClick={confirmImport}>
            {busy() ? 'Importing…' : 'Confirm Import'}
          </button>
          <button class="btn-import" onClick={reset}>Start Over</button>
        </section>
      )}
    </div>
  );
}

// Conversational bundle drafting — mirrors CharCreate.jsx's AIBuilder exactly
// (streaming chat via callProvider, a system prompt, a fenced JSON block
// extracted by regex). The generated JSON is handed to the parent's
// handleGenerated(), which runs it through the same validateBundle() preview
// every file import goes through — this path never bypasses that gate.
function BundleAIBuilder(props) {
  const [messages, setMessages] = createSignal([]);
  const [input, setInput] = createSignal('');
  const [streaming, setStreaming] = createSignal(false);
  let controller = null;

  async function send() {
    const text = input().trim();
    if (!text || streaming()) return;
    setInput('');

    const newMsgs = [...messages(), { role: 'user', content: text }];
    setMessages(newMsgs);
    setStreaming(true);

    const aiMsgs = newMsgs.map(m => ({ role: m.role, content: m.content }));
    controller = new AbortController();

    try {
      const stream = callProvider(aiMsgs, BUNDLE_BUILDER_SYSTEM, controller.signal);
      let full = '';
      setMessages([...newMsgs, { role: 'assistant', content: '' }]);

      for await (const chunk of stream) {
        full += chunk;
        setMessages([...newMsgs, { role: 'assistant', content: full }]);
      }

      const jsonMatch = full.match(/```BUNDLE_JSON\s*([\s\S]*?)```/);
      if (jsonMatch) {
        try {
          const json = JSON.parse(jsonMatch[1].trim());
          props.onGenerated(json);
        } catch (_) {}
      }
    } catch (e) {
      if (e.name !== 'AbortError') {
        setMessages([...newMsgs, { role: 'assistant', content: `Error: ${e.message}` }]);
      }
    } finally {
      setStreaming(false);
      controller = null;
    }
  }

  return (
    <div class="ai-builder">
      <div class="builder-messages">
        <Show when={messages().length === 0}>
          <div class="builder-hint">What do you want to add to your campaign? An NPC, a location, an encounter, an adventure hook, a house rule — describe it and I'll help flesh it out.</div>
        </Show>
        <For each={messages()}>
          {(msg) => (
            <div class={`builder-msg builder-msg-${msg.role}`}>
              {msg.content.replace(/```BUNDLE_JSON[\s\S]*?```/g, '[Content drafted! See preview below]')}
            </div>
          )}
        </For>
      </div>
      <div class="builder-input-row">
        <input
          class="builder-input"
          placeholder="Describe the content..."
          value={input()}
          onInput={(e) => setInput(e.target.value)}
          onKeyDown={(e) => e.key === 'Enter' && send()}
        />
        <button class="builder-send" onClick={send} disabled={streaming()}>
          {streaming() ? '...' : 'Send'}
        </button>
      </div>
    </div>
  );
}
